version: '3'
services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - .:/app
    ports:
      - "8081:8081" # Exposing Metro bundler port
    stdin_open: true
    tty: true
    